### ISSUE TITLE
Artifacts plugin ignores imports on client (but not on server)

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#1287]
artifact 1:
```yaml
name: Custom.TheOneWithTheExport
export: |
  LET X <= SELECT * FROM info()
```
artifact 2:
```yaml
name: Custom.TheOneWithTheImport
imports:
  - Custom.TheOneWithTheExport
sources:
  - query: |
      SELECT * FROM X
```
artifact 3:
```yaml
name: Custom.CallArtifactWithImports
type: CLIENT
sources:
  - query: |
      select * from Artifact.Custom.TheOneWithTheImport()
```
This last "artifact 3" produces no results.

However when it's equivalent is run on the server it does produce the expected result. 

```yaml
name: Custom.CallArtifactWithImports
type: SERVER
sources:
  - query: |
      select * from Artifact.Custom.TheOneWithTheImport()
```

Also `SELECT * FROM Artifact.Custom.CallArtifactWithImports()` produces results when run on the server, but not on the client.
