### ISSUE TITLE
Date field used as a parameter, can not type the date and time properly.

### ISSUE THREAD

**Issue by fffecher** [Velocidex/velociraptor#1294]
I am creating a new artifact and I am not able to type date and time properly when my parameter is timestamp type.

When I try to change the time, I never get the number I am typing. Also, I don't see how I can use the clock picture, it doesn't help me with this data entry.

Attached, you can see an image of this specific field.

![image](https://user-images.githubusercontent.com/91761192/135687304-684f5f2e-4d76-4fd7-b80e-1ff9af792592.png)

I appreciate any help to fix this data entry. Thank you. Fernando.

**Comment by predictiple** [comment]
As a workaround you could change the date parameters to be strings and then convert them to timestamps in the VQL.

For example:

```yaml
parameters:
   - name: DateInitial
   - name: DateEnd

sources:
  - query: |
      LET date_initial <= timestamp(string=DateInitial)
      LET date_end <= timestamp(string=DateEnd)
      SELECT format(format="%v is %T", args=[date_initial,date_initial]) AS DateInitial,
             format(format="%v is %T", args=[date_end,date_end]) AS DateEnd
      FROM scope()
```
