### ISSUE TITLE
Feature request: improved capability to browse and download collection

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#135]
I would like to raise a feature request for improved artefact download in the GUI from completed flows.

Currently we can download the whole flow as an archive file but we can not browse and download an individual upload in the flow. It would be really nice to enable this in the GUI so I could setup automatic processing on some of the collection, then download via the GUI for my manual tasks after an initial triage.

Example expected workflow:

Run KapeFile artefact in flow.
Automatically parse triage timeline from flow
Manually download individual uploads from the flow for addition process / analysis (through the GUI).

**Comment by scudette** [comment]
At a previous job we mapped the file store via webdav then just mounted the whole thing on a windows workstation. This allows to just copy the files you need via explorer (you can technically directly run tools on the mounted filesystem but its pretty slow due to network latency).

It is quite easy to set it up:
1. Just set up Apache with webdav and authentication mapping the filestore clients directory. Make it listen on localhost.
2. Configure the reverse proxy feature in the server config file to map a path to the Apache server.
3. Point explorer (or a browser works too) to the path.

You get SSL for free because Velociraptor will be doing the proxying. 

Auth is a bit more complicated:

1. If you use basic auth (i.e. Velociraptor is managing the username/passwords) then you can enable auth on the reverse proxy.
2. If you use SSO then you have to turn off auth and get Apache to use basic auth. This is because we found the most webdav clients (i.e. windows explorer) do not support sso and only support basic auth over ssl.

This is how you enable this kind of setup:
```
GUI:
  reverse_proxy:
  - route: /files/
    url: http://localhost:XXX/webdav/    <--- port for Apache
    require_auth: true
```

Of course if you just want to browse the files and not use webdav you can already just map the clients directory through the reverse proxy. For example:

```
GUI:
  reverse_proxy:
  - route: /files/
    url: file:///path_to_filestore/clients/
    require_auth: true
```

Will allow you to access all the files for each client (including upload) e.g. https://localhost:8889/files/C.4f5e52adf0a337a9/uploads/F.BMMQFOR632IEA/ntfs/C%253A/Users/test/NTUSER.DAT
