### ISSUE TITLE
separate certificates from main config file

### ISSUE THREAD

**Issue by juju4** [Velocidex/velociraptor#1377]
When using tools like ansible, puppet and similar, config files are managed with templates.
With velociraptor including directly certificates inside, it makes it harder to manage velociraptor with those tools.
It would be great that like grr previously to make use of include and allow to generate only certificates and send it to a dedicate config file that is included in main config file.
same could apply to other secrets
even better if the `config generate` had a separate `secrets generate`.

Example
* currently
```
version:
  name: velociraptor
  version: 0.6.1
  commit: 58295e70
  build_time: "2021-09-09T12:14:06+10:00"
Client:
  server_urls:
  - https://172.17.0.2:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    [REDACTED]
    -----END CERTIFICATE-----
  nonce: YPlCdjP+bM8=
  writeback_darwin: /etc/velociraptor.writeback.yaml
[...]
```
* possibly
```
version:
  name: velociraptor
  version: 0.6.1
  commit: 58295e70
  build_time: "2021-09-09T12:14:06+10:00"
Client:
  server_urls:
  - https://172.17.0.2:8000/
  ca_certificate: filename|file
  nonce:
    include: /etc/velociraptors/secrets-nonce
  writeback_darwin: /etc/velociraptor.writeback.yaml
[...]
```

Thanks a lot for your work!

**Comment by scudette** [comment]
There is no reason I can think of to manage the Velociraptor certificates outside of the program. In fact it will not work if you try to do it because Velociraptor requires the certificates be issued by the same Velociraptor CA certificates.

You can specify external certificates for TLS via the `Frontend.tls_certificate_filename` which **can** be managed externally but this **must** be a properly issued certificate (e.g. lets encrypt or purchased cert) - It can not be self signed.

https://github.com/Velocidex/velociraptor/blob/master/config/proto/config.proto#L509

You can always read out the certificates from the yaml file using `config show` command for example to inspect the X509 properties for the frontend certificate:

```
velociraptor config show --json  | jq -r .Frontend.certificate | openssl x509 -text
```

So if we allowed the change you propose it wont help people manage the certs any better (because they wont be able to mint them anyway) but will only add to confusion (because people will try).

**Comment by juju4** [comment]
I'm not looking to manage/create certificates outside of velociraptor, just store them in separate file and that's why suggested a `velociraptor secrets generate` or `velociraptor certificates generate`.
Making a separate file makes easier to manage by provisioning tools.
It does not need to be the default, it can be optional (`velociraptor config generate --without-secrets` 
+ `velociraptor secrets generate`).

Take this ansible role steps
https://github.com/PrymalInstynct/ansible_velociraptor/blob/main/tasks/install/install_server.yml
it does `velociraptor config generate` and after a bunch of string replacement to match targeted config on the orchestrator before copying it to target system.
with requested feature, it could be simpler like
```
- name: "Install Server | Generate Velociraptor Server Config"
  shell: "{{ velociraptor_dir }}/velociraptor certificates generate > /etc/velociraptor/certificates.yaml"
  args:
    creates: /etc/velociraptor/certificates.yaml

- name: "Install Server | Set Velociraptor Server Config"
  template:
    src: server.config.yaml.j2
    dest: "/etc/velociraptor/server.config.yaml"
    mode: '0644'
    owner: root
```
the template server.config.yaml.j2 would just need to include certificates.yaml which is managed/created by velociraptor while the main server.config.yaml file is managed by provisioner (template obviously based on velociraptor config)
