### ISSUE TITLE
MFT Fixup error

### ISSUE THREAD

**Issue by yarox24** [Velocidex/velociraptor#1562]
Hi,

Version of Velociraptor on client and server was 0.6.2

Client OS: Microsoft Windows 10 Pro 10.0.19044 Build 19044 (x64)

IncludeVSS parameter was set to False.

We developed custom CLIENT type VQL plugin with following source:

```
name: Custom.Windows.XXX.YYYY.KapePreconfigured
description: |
   ZZZZ

type: CLIENT

parameters:
  - name: IncludeVSS
    description: Gather even more data by including Volume Snapshot Service
    type: bool
    default: N
    
    
precondition:
      SELECT OS From info() where OS = 'windows'

sources:
    - query: |
        SELECT * FROM Artifact.Windows.KapeFiles.Targets(VSSAnalysis=IncludeVSS,DontBeLazy=true,_MFTMirr=true,Amcache=true,Ammyy=true,Antivirus=true,AnyDesk=true,ApacheAccessLog=true,AppData=true,ApplicationEvents=true,AsperaConnect=true,BITS=true,BitTorrent=true,BrowserCache=true,CertUtil=true,Chrome=true,ChromeExtensions=true,ChromeFileSystem=true,CloudStorage=true,CombinedLogs=true,ConfluenceLogs=true,DC__=true,Debian=true,Edge=true,EdgeChromium=true,EvidenceOfExecution=true,Exchange=true,ExchangeClientAccess=true,ExchangeCve_2021_26855=true,ExchangeTransport=true,FTPClients=true,FileSystem=true,FileZillaClient=true,FileZillaServer=true,Firefox=true,GroupPolicy=true,IISLogFiles=true,InternetExplorer=true,JavaWebCache=true,LNKFilesAndJumpLists=true,LinuxOnWindowsProfileFiles=true,LogFiles=true,MOF=true,MemoryFiles=true,MicrosoftOneNote=true,MicrosoftStickyNotes=true,MicrosoftTeams=true,MicrosoftToDo=true,NGINXLogs=true,Notepad__=true,OpenSSHClient=true,OpenSSHServer=true,OpenVPNClient=true,Opera=true,OutlookPSTOST=true,P2PClients=true,PowerShellConsole=true,Prefetch=true,RDPCache=true,Radmin=true,RecentFileCache=true,RecycleBin=true,RegistryHives=true,RemoteAdmin=true,DirectoryTraversal_SQLiteDatabases=true,SRUM=true,ScheduledTasks=true,Skype=true,TeamViewerLogs=true,ThumbCache=true,TorrentClients=true,Torrents=true,USBDevicesLogs=true,VMware=true,VMwareInventory=true,VMwareMemory=true,VNCLogs=true,VirtualBox=true,VirtualBoxConfig=true,VirtualBoxLogs=true,VirtualBoxMemory=true,WBEM=true,WER=true,WSL=true,WebBrowsers=true,WebServers=true,WinSCP=true,WindowsFirewall=true,WindowsIndexSearch=true,WindowsNotificationsDB=true,WindowsOSUpgradeArtifacts=true,WindowsTimeline=true,XPRestorePoints=true,mRemoteNG=true,qBittorrent=true,uTorrent=true)
```

but it turns out it's loses some files which is visible in logs:
```
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01.log: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01.log: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.dat: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.dat: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.jfm: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.jfm: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\ntuser.dat.LOG2: open C:\\Users\\live\\ntuser.dat.LOG2: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\NTUSER.DAT: open C:\\Users\\live\\NTUSER.DAT: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat.LOG1: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat.LOG1: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat.LOG2: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat.LOG2: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5: Access is denied., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\ntuser.dat.LOG1: open C:\\Users\\live\\ntuser.dat.LOG1: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01tmp.log: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01tmp.log: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.jfm: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.jfm: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01.log: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01.log: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.dat: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.dat: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}
{"_ts":1643140639,"client_time":1643131311,"level":0,"message":"vql: upload: Unable to open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01tmp.log: open C:\\Users\\live\\AppData\\Local\\Microsoft\\Windows\\WebCache\\V01tmp.log: The process cannot access the file because it is being used by another process., unable to fall back to ntfs parsing: Fixup error with MFT 5\n"}

```

but in the same time if problematic paths are split into smaller queries using KapeFiles.Targets everything works smoothly:

- `SELECT * FROM Artifact.Windows.KapeFiles.Targets(VSSAnalysis=IncludeVSS,DontBeLazy=true,RegistryHives=true)`

- `SELECT * FROM Artifact.Windows.KapeFiles.Targets(VSSAnalysis=IncludeVSS,DontBeLazy=true,WebBrowsers=true)`

and previous Fixup error with MFT is gone and files are uploaded properly.
