### ISSUE TITLE
Issue with glob in Notebook for 'deaddisk --add_windows_directory' on v0.6.4-rc3

### ISSUE THREAD

**Issue by teddy-ROxPin** [Velocidex/velociraptor#1717]
When I attempt to use a glob further than just 'C:/' I am met with an error when using a Notebook after a gui launch using a remap file output from 'deaddisk --add_windows_directory'

This works without error:
```
SELECT * FROM glob(globs='C:/')
```

The following thows an error of `Globber: open /ouput/C\: The system cannot find the path specified. while processing C:`
```
SELECT * FROM glob(globs='C:/Users')
```

Drive remapping section from the 'deaddisk --add_windows_directory' output I'm using (yes, I forgot the 't' in output :) ):
```
- type: mount
  description: 'Mount the directory .\ouput\C\ on the C: drive (NTFS)'
  from:
    accessor: file
    prefix: .\ouput\C\
  "on":
    accessor: ntfs
    prefix: '\\.\C:'
    path_type: ntfs
- type: mount
  description: 'Mount the directory .\ouput\C\ on the C: drive (FILE Accessor)'
  from:
    accessor: file
    prefix: .\ouput\C\
  "on":
    accessor: file
    prefix: 'C:'
    path_type: windows
- type: mount
  description: 'Mount the directory .\ouput\C\ on the C: drive (Auto Accessor)'
  from:
    accessor: file
    prefix: .\ouput\C\
  "on":
    accessor: auto
    prefix: 'C:'
    path_type: windows
```
