### ISSUE TITLE
Monitoring configuration - field Events not found in type proto.Config

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#18]
Hi, 
I am reading "crikeycon_2019.pdf" and there it says that for Event monitoring we should add artifacts into Events section. In Yaml there is no Events section, so I recreate it like in "crikeycon_2019.pdf" and then I got error. 

```
./velociraptor-v0.3.0-linux-amd64 --config velociraptor.config.yaml frontend -v
velociraptor-v0.3.0-linux-amd64: error: Unable to load config file: yaml: unmarshal errors:
  line 194: field Events not found in type proto.Config
```

Sample Added Code

```
Events:
  artifacts:
    - Windows.Events.ServiceCreation
 version: 2
```
