### ISSUE TITLE
Upload deduplication is not working properly

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#2489]
Test case 

```yaml
name: Custom.TestDuplication
parameters:
   - name: myGlobs
     type: csv
     default: |
       Glob
       Windows/Notepad.exe
       Windows/Notepad*

sources:
  - query: |
      SELECT * FROM Artifact.Generic.Collectors.File(Root="C:", Accessor="auto", collectionSpec=myGlobs)
```

Uploads the same file twice

![Win_Server_2019_2](https://user-images.githubusercontent.com/3856546/222448401-695eab92-e3f3-4642-8f93-9b2c18b2c63f.png)

![Win_Server_2019_2](https://user-images.githubusercontent.com/3856546/222448450-358d2e67-427e-4127-8c7d-6865d04d4a04.png)

Reported by @hunt3vil
