### ISSUE TITLE
Hunt results return extra rows when run across orgs.

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3072]
In 0.7.0-3 with several organisations set up, running a hunt in \<root\> + the additional organisations causes duplicate rows to be returned for client in the organisations. This is easily tested with `velociraptor gui` and a dummy artifact like

```yaml
name: Dummy
description: |
   Return a single dummy row

# Can be CLIENT, CLIENT_EVENT, SERVER, SERVER_EVENT
type: CLIENT

sources:
  - precondition:
      SELECT OS From info() where OS = 'windows' OR OS = 'linux' OR OS = 'darwin'

    query: |
      SELECT 1, 2 FROM scope()
```

1. Run `velociraptor gui`
2. Download the client config for the ACME Inc org. from the dashboard (press the home icon)
3. Run a new client for the ACME Inc org.: `velociraptor client --config ~/Downloads/client.O123.config.yaml`
4. Import the dummy artifact (in the root org.) or just continue with any artifact that returns rows
5. Create a hunt and run it in all organisations
6. As expected, each client returns the expected number of rows in the root org. (one row for the dummy artifact)
7. In the ACME Inc org., each client returns two rows
8. If additional organisations are created with new clients, and a hunt is run across all orgs., then root still returns one row, ACME returns two rows, the new orgs. return n+1 rows, i.e. the first org. created after ACME Inc produces three rows.

The screenshots show the hunt notebooks. The individual client flows also shows incorrect number of rows, and the same does TotalRows.

Root org. with one row returned, as expected:
![2023-11-04_17-38_1](https://github.com/Velocidex/velociraptor/assets/4006538/0b5e507a-d1c4-4c00-a718-016b844f6973)

Org. no. 1 with two rows returned:
![2023-11-04_17-37](https://github.com/Velocidex/velociraptor/assets/4006538/a9135856-cca7-4254-af48-022ea794f76f)

Org. no. 2 with three rows returned:
![2023-11-04_17-38](https://github.com/Velocidex/velociraptor/assets/4006538/46e25a0f-bd3d-4b83-a9f7-eb196c439cf7)
