### ISSUE TITLE
vql precondition troubles with negation

### ISSUE THREAD

**Issue by sec-hbaer** [Velocidex/velociraptor#3257]
Hi, I am having troubles with using preconditions in VQL.

I have reduced my planned artifact to following proof of concept:

```
name: Custom.Precondition.POC
author: sec-hbaer
description: |
   poc of my problem
   
type: CLIENT
   
parameters:
   - name: Uninstall
     type: bool
     default: false

sources:
  - name: WindowsTest
    precondition: 
      SELECT OS FROM info() WHERE OS = 'windows' AND NOT Uninstall
    query: |
      SELECT * FROM execve(argv=['powershell.exe', 'Write-Host foobar'])
```

Running the artifact as is, I would expect the query to be executed. But the query is skipped due to precondition. 
The problem to me seems to be the `NOT` in the precondition, as leaving it out, the precondition behaves as the logic would suggest.

I have tested it on windows amd64 running velociraptor v0.6.7-4 and v0.7.1-1

I would appreciate pointers to what I'm doing wrong :)
