### ISSUE TITLE
Prefetch panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by prolsen** [Velocidex/velociraptor#335]
I was running this on a remote host so I don't have any data from the host this failed on. It works fine on several test instances prior to running it on said remote host. The remote host is Windows 10 Pro. The test systems that worked fine are Windows 10 Pro VMs.

Out of 6 non-test systems, this occurred on 3 of the 6. The other 3 finished fine. All appear to be of similar builds, but again, I have no visibility into the system specifics outside of the OS unfortunately. 

**Custom Artifact:**

```
name: Custom.Windows.Forensics.Prefetch
description: |
  <snip>

parameters:
    - name: prefetchGlobs
      default: C:\Windows\Prefetch\*.pf

sources:
  - precondition: SELECT OS From info() where OS = 'windows'
    queries:
      - |
        SELECT * FROM foreach(
          row={
             SELECT * FROM glob(globs=prefetchGlobs)
          },
          query={
             SELECT LastRunTimes[0] as timestamp,
                    LastRunTimes[0] as lastrun_time,
                    Name AS file_name,
                    Executable as exe, 
                    FileSize as file_size, 
                    LastRunTimes as lastrun_times,
                    RunCount as run_count
             FROM prefetch(filename=FullPath)
          })
```

**Using a local collector:**

```
autoexec:
    argv: ["artifacts", "collect", "-v", "WindowsLocalCollection", "--password", "mehmeh", "--output", "C:\\Windows\\Temp\\Test_Collection_$COMPUTERNAME.zip"]
    
    artifact_definitions:
      - name: WindowsLocalCollection
        description: Testing
        precondition: SELECT OS From info() where OS = 'windows'

        sources:
          - name: Prefetch
            queries:
              - SELECT * FROM Artifact.Custom.Windows.Forensics.Prefetch()
```

**Error:**

```
panic: runtime error: index out of range [1] with length 1
goroutine 5154 [running]:
www.velocidex.com/golang/go-prefetch.PrefixCodeTreeRebuild(0xc0016a7ba5, 0x1, 0x2a0e5, 0x1e2ea01)
	/tmp/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20190703150313-0469fa2f85cf/lzxpress.go:131 +0x2a8
www.velocidex.com/golang/go-prefetch.LZXpressHuffmanDecompressChunk(0x3ba5, 0xc0016a4000, 0x3ba6, 0x2dc8a, 0x1a1f7, 0xc001866000, 0x2dc8a, 0x2dc8a, 0x10000, 0x3ba5, ...)
	/tmp/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20190703150313-0469fa2f85cf/lzxpress.go:204 +0x7a
www.velocidex.com/golang/go-prefetch.LZXpressHuffmanDecompress(0xc0016a4000, 0x3ba6, 0x2dc8a, 0x2dc8a, 0x8, 0x3ba6, 0x1e2ea80, 0xc00006c060, 0xc000e19e01)
	/tmp/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20190703150313-0469fa2f85cf/lzxpress.go:281 +0xcc
www.velocidex.com/golang/go-prefetch.LoadPrefetch(0x1e31080, 0xc00063c060, 0xc00063c060, 0x1e31080, 0xc00063c060)
	/tmp/go/pkg/mod/www.velocidex.com/golang/go-prefetch@v0.0.0-20190703150313-0469fa2f85cf/prefetch.go:26 +0xe36
www.velocidex.com/golang/velociraptor/vql/parsers._PrefetchPlugin.Call.func1.1(0xc0002a6dc0, 0xc0007ccdb0, 0x1e5db80, 0xc000919080, 0xc0011e7f88, 0xc001cb5e00)
	/build/vql/parsers/prefetch.go:83 +0x357
www.velocidex.com/golang/velociraptor/vql/parsers._PrefetchPlugin.Call.func1(0xc001cb5e00, 0xc0002a6dc0, 0xc0001d2640, 0x1e5db80, 0xc000919080)
	/build/vql/parsers/prefetch.go:91 +0x169
created by www.velocidex.com/golang/velociraptor/vql/parsers._PrefetchPlugin.Call
	/build/vql/parsers/prefetch.go:45 +0x8b
Could Not Find c:\Windows\Temp\TESTING_*.zip
```
