### ISSUE TITLE
Bug: Artifact errors using collect() Plugin

### ISSUE THREAD

**Issue by FabFaeb** [Velocidex/velociraptor#3508]
On version 0.72.0 when creating an artifact using the `collect()` plugin, internal artifacts can not be correctly collected.
How to reproduce:
Create a minimal test artifact like
```
name: Custom.Test.Artifact
description: |
   This is the human readable description of the artifact.

sources:
    - name: Test
      query: |
        SELECT * FROM collect(artifacts="Generic.Collectors.File")
```
and run it on a connected client.
This will produce the error  message `collect: Unknown artifact Generic.Collectors.File` in the logs. Before version 0.72.0 this worked fine.

This bug was already confirmed by  @predictiple (see also discord conversation below https://discord.com/channels/624244632552734750/865024982399320114/1242797063079592006).

Important note: When running the same query in a notebook on the server, everything still works as expected.
Maybe this is related to https://github.com/Velocidex/velociraptor/issues/3299 ?
