### ISSUE TITLE
Remapping impersonation rules sometimes ignored

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3640]
version: 0.72.4
commit: 05563cc
build_time: "2024-07-23T03:30:33Z"
ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/10052204049

run on Linux with the following remapping config:

```yaml
remappings:
  - type: permissions
    permissions:
    - COLLECT_CLIENT
    - FILESYSTEM_READ
    - FILESYSTEM_WRITE
    - READ_RESULTS
    - MACHINE_STATE
    - SERVER_ADMIN
    - COLLECT_SERVER
    - EXECVE
  - type: impersonation
    os: windows
    hostname: barney
    env:
    - key: SystemRoot
      value: C:\Windows
    - key: WinDir
      value: C:\Windows
    disabled_functions:
    - amsi
    - lookupSID
    - token
    disabled_plugins:
    - users
    - certificates
    - handles
    - pslist
    - interfaces
    - modules
    - netstat
    - partitions
    - proc_dump
    - proc_yara
    - vad
    - winobj
    - wmi
```

shows the impersonated client info, as expected. Performing manual interrogations (Generic.Client.Info) does not alter the client info, also as expected.

However restarting the client with the same remapping ignores the impersonation rules and updates the server with the real client info. Manual interrogations correctly show the impersonated info but do not update the server's client info.

Another user has reported possibly related behaviour with version 0.72.3 where the impersonated info is updated spontaneously with the real client info but they said that manual interrogation restores the impersonated info.
