### ISSUE TITLE
Notebook vql_suggestions do not show up in client events notebooks

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3833]
If I copy a notebook type vql_suggestion from a client artifact to a client event artifact, I expect it to work just the same: Show up as a suggestion in the "plus" menu. However, the list of suggestions is empty in the client events notebook.

**Comment by scudette** [comment]
I can not replicate this - take the following client event artifact for example

```yaml
name: Custom.TestEvent
type: CLIENT_EVENT

sources:
  - query: |
      SELECT Unix FROM clock()
    notebook:
    - type: vql_suggestion
      name: Get Info
      template: SELECT * FROM info()
```

After installing it into the client monitoring table, I can see the suggestion
