### ISSUE TITLE
Broken OIDC integration with Dex

### ISSUE THREAD

**Issue by jfstenuit** [Velocidex/velociraptor#4001]
In my set-up, I have Velociraptor served under /vraptor and Dex served under /auth. NginX takes care of serving the requests to the correct back-end. (Dex is an OIDC IdP written in Go).

Velociraptor configuration is as follow : 
```
GUI:
  bind_address: 127.0.0.1
  bind_port: 8889
  use_plain_http: true
  base_path: /vraptor
  gw_certificate: |
redacted
  gw_private_key: |
redacted
  public_url: https://host.domain.tld/vraptor
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url:
redacted
    type: sidebar
    new_tab: true
  authenticator:
    type: oidc
    oidc_issuer: https://host.domain.tld/auth
    oauth_client_id: velociraptor-client
    oauth_client_secret: redacted
```
The IDP respond properly at https://host.domain.tld/auth/.well-known/openid-configuration

But velociraptor never tries to reach the OIDC `authorization_endpoint` URL. When clicking on "Sign in with Generic OIDC Connector" on page https://host.domain.tld/vraptor/app/index.html , the url requested is https://host.domain.tld/vraptor/vraptor/auth/oidc/login which directly 302-redirects to /vraptor/app/index.html .

There is no indication of an error in the OIDC configuration, neither trough the GUI nor through the logs. 

If there is something broken with the OIDC IdP (either because of the configuration of Velociraptor or because of the features supported by the IdP), there should at least be an indicative message in the logs.
