### ISSUE TITLE
Default timestamp can cause white page

### ISSUE THREAD

**Issue by FormindMPO** [Velocidex/velociraptor#4003]
When creating a custom Artifact, and using a timestamp parameter

```yml
parameters:
  - name: MoreRecentThan
    default: <any not valid str but not "2025-">
    type: timestamp
```` 

The artifact is successfully saved, but causes crash upon hunt creation (seems to be on the parameter display of artifact details):

![image](https://github.com/user-attachments/assets/95797efb-a962-48dd-909b-1f621e0b9d6c)
![image](https://github.com/user-attachments/assets/535ad73a-d3f6-4bad-8ae1-8c7ff77e6cbe)

____

To reproduce :

1. Create a custom artifact with a broken timestamp parameter
```
name: Test
parameters:
  - name: Param1
    default: willBreak
    type: timestamp

sources:
  - query: |
      SELECT * FROM clients() WHERE last_seen_at > Param1
```
2. Create a hunt, click on this artifact
![image](https://github.com/user-attachments/assets/1e562f1b-aa97-46f1-b242-5a0dcf1686f8)
3. Now you have a whitepage, nothing works (even refresh - F5), you'll have to go back to the / (home) page
