### ISSUE TITLE
Check OAuth token for roles

### ISSUE THREAD

**Issue by tapioca-sublime** [Velocidex/velociraptor#4060]
After a successful OAuth SSO could it be checked if the received token has a role property?

This could allow the Velociraptor server to add the authenticated user into its list using that role (a.g. reader or investigator) as opposed of prompting the user to reach out its administrator to add them as a Velociraptor GUI user

**Comment by scudette** [comment]
We specifically do not want to allow the SSO admin to add users into Velociraptor groups - this can lead to privilege escalations.

I dont think the major cloud providers have a mechanism to assign roles into the oauth token do they?

**Comment by tapioca-sublime** [comment]
The Azure OpenID mechanism allows local roles to be added to the JWT token like in the example below. Would your design choices exclude this possibility even for just the Velociraptor reader role?

```
"aud": "11112222-bbbb-3333-cccc-4444dddd5555",
"iss": "https://login.microsoftonline.com/833ced3d-cb2e-41de-92f1-29e2af035ddc/v2.0",
"iat": 1670826509, "nbf": 1670826509, "exp": 1670830409,
"name": "Kyle Marsh",
"oid": "bbbbbbbb-1111-2222-3333-cccccccccccc",
"preferred_username": "kylemar@idfordevs.dev",
"roles": [
 "Approver",
 "Reviewer" 
],
"sub": "dx-4lf-0loB3c3uVrULnZ2VTLuRRWYff0q7-QlIfYU4",
"tid": "ccccdddd-2222-eeee-3333-ffff4444aaaa",
```

Docs:
- https://learn.microsoft.com/en-us/security/zero-trust/develop/configure-tokens-group-claims-app-roles#groups-and-app-roles

- https://learn.microsoft.com/en-us/entra/identity-platform/howto-add-app-roles-in-apps#usage-scenario-of-app-roles

**Comment by scudette** [comment]
I can not actually test this because it seems this feature is only available when you have Microsoft Entra . I just submitted a change that should make it much easier to debug through oauth issues like this.

Can you please test with the latest build  that includes https://github.com/Velocidex/velociraptor/commit/ac00f9dcc86500f356b097ebd9e0a8d259db48aa

It should work. You can enable more debugging too now so you can see the exact claims coming back from the IDP

```yaml
- type: oidc 
  oidc_name: AzureOIDC 
  oidc_issuer: https://login.microsoftonline.com/<tenant ID>/v2.0
  oauth_client_id: <client id>
  oauth_client_secret: <client secret>
  # To enable debugging 
  oidc_debug: true
  claims: 
     # This reads roles from a claim named "roles"
     roles: roles
     role_map:
          # This maps the custom role to a list of Velociraptor
          # roles. NOTE: Users can have additional roles granted in the
          # GUI this is a minimum set.
          Velociraptor.User:
            roles:
            - reader
```

You have to add the custom role Velociraptor.User to Azure then when the user logs in they will get the reader role according to the mapping in the config file.
