### ISSUE TITLE
Update to Velociraptor 073.4 - Unknown plugins error

### ISSUE THREAD

**Issue by pglanzer2025** [Velocidex/velociraptor#4138]
After upgrading added allowed plugins create an error during the start of the velociraptor service
examples:
velociraptor: error: frontend: starting frontend: Unknown plugin execve
velociraptor: error: frontend: starting frontend: Unknown plugin artifact_definitions

**Comment by scudette** [comment]
Thanks for reporting this. 

As of 0.73.4 we moved from specifying an allow list which explicitly lists every plugin to a deny list which just denies those risky plugins like execve(). This should hopefully make it a lot easier to manage going forward.

The code is supposed to handle the old way or the new way so this is definitely a bug but you can switch to the new way by replacing the allow list with a deny list:

```yaml
  denied_plugins:
     - execve
     - http_client
    
 denied_functions:
    - upload_s3

 denied_accessors:
   - s3
   - sftp
  
```
