### ISSUE TITLE
Feature request: hunt scheduling

### ISSUE THREAD

**Issue by h4sh5** [Velocidex/velociraptor#628]
Velociraptor is an amazing tool for on-demand DFIR, but I think it has a lot of potential to become a scalable monitoring tool as well. The nature of the tool feels a lot like osquery + fleet (but velociraptor is simpler and has better deployment imo).

If users can schedule regular hunts to be performed on hosts, and those results can be displayed on the hunt manager so that the user can go back in time and see hunt results, they can have historical view and use it for monitoring.

This can be added as a new input field under "new hunt", below the "expiry" date, with a "recurring hunt" input. 
![image](https://user-images.githubusercontent.com/38898566/92512878-d00d6400-f252-11ea-8b36-6f2385594b81.png)

Example flow:
Hunt manager -> new hunt -> select artifacts
  -> recurring hunt checkbox (tick) -> every X seconds/minutes/hours/etc. -> next
if recurring check box is ticked, pop up window: "start scheduled hunt now?" yes/no
     -> user clicks yes: hunt starts
     -> user clicks no: hunt is added, wait for user to click start button as usual

After that, the hunt will run every X interval and a row added to the hunt manager table, so the user can search back in time and look at results. Maybe goroutines and timeouts will make it easy to implement?

**Comment by scudette** [comment]
This is an excellent question we should probably have it on the wiki.

You can already do this via a server artifact. Just add an artifact like this:

```yaml
name: Custom.RunInfo
description: |
   Run client interrogation periodically

type: SERVER_EVENT
parameters:
- name: DayRegex
  default: Tuesday
- name: TimeRegex
  default: "01:28:"

sources:
  - query: |
      LET schedule = SELECT UTC.String AS Now, 
           Weekday.String AS Today 
      FROM clock(period=60)
      WHERE Now =~ TimeRegex AND Today =~ DayRegex

      SELECT hunt(artifacts=["Generic.Client.Info"], 
             description="Periodic info hunt") FROM schedule
```

Then go to the server monitoring screen in the GUI and add this new artifact.  This query will start a new hunt every week by default at 1:28 UTC.

The way it works is that the clock() plugin will generate a new event (a new row) every 60 seconds. We then filter out all the rows that do not match our criteria using regexes and save the query in the schedule variable.

Then we just iterate over each row from the schedule query and launch a hunt with the specified artifacts.

You don't strictly need to filtering rows etc - you can just give the clock plugin a period of a week say but this means that every time you restart the server it will start again so hunt times are not as accurate or predictable.
