### ISSUE TITLE
Implement types for artifact parameters

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#795]
Currently artifact parameters are always strings, which means that artifacts have to explicitly convert them to whatever type is needed. 

The artifact YAML allows parameters to specify a type, but this only controls the GUI form element that is used to select the value - for example a `type: timstamp` causes the GUI to present a datetime selector - however the client still receives a string as the value of the parameter. This is confusing as the artifact writer needs to explicitly convert to a timestamp before using it.

The reason for the parameters being a string is that the request is sent in a protobuf and the parameters needs to have a specific type. However we can always take care of the type conversion in the artifact compiler code any way, which can automatically add the conversion code as needed:

```yaml
parameters:
   - name: Foo
     type: timestamp

sources:
- query: |
      LET Foo <= timestamp(epoch=Foo)   <--- automatically added by the compiler
....
```

This solution means that Foo can be used right away as a timestamp. The behavior is more consistent and finally this will work seamlessly on older clients since it does not change any client code.
