### ISSUE TITLE
Options pack GUI form element

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#865]
Sometimes we need to group together a bunch of settings in a convenient way. For example some artifacts take a huge number of parameters all related together.

This feature request is to define a GUI form type that collapses multiple parameters together. The artifact parameter may be defined as:

```yaml
parameters:
  - name: MyName
    description: ....
   type: json
   choices:
      - name: First
        type: int
      - name: Second
        description: Some description.
```

Inside the artifact this should present as a dict that can be accessed as:
```sql
SELECT MyName.First FROM ....
```

The GUI should show a collapsible form group that can be hidden/shown and appear distinct because all these are related.
