### ISSUE TITLE
Re think the implementation of preconditions

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#930]
The way preconditions are implemented now have a few shortcomings

1. Preconditions don't stop evaluation of <= let queries
2. Preconditions are applied when calling an artifact through the Artifact plugin. This makes it impossible to use a windows sub Artifact on linux even if we can adjust paths etc.

**Comment by predictiple** [comment]
```yaml
name: cpu_count
description: |
  This artifact returns the number of CPU cores and is intended to be called by
  other artifacts that need to set the foreach functions's "workers" parameter.

type: CLIENT

sources:

  - name: test_linux
    precondition: SELECT OS FROM info() WHERE OS = "linux"
    query: |
      LET cmd_result <= SELECT Stdout FROM execve(argv=["lscpu", "-p=cpu"])
      SELECT count() AS cores FROM parse_lines(filename=cmd_result[0].Stdout, accessor="data")
      WHERE Line AND NOT Line =~ "^#"
      GROUP BY 1

  - name: test_windows
    precondition: SELECT OS FROM info() WHERE OS = "windows"
    query: |
      SELECT environ(var="NUMBER_OF_PROCESSORS") AS cores FROM scope()

  - name: test_mac
    precondition: SELECT OS FROM info() WHERE OS = "darwin"
    query: |
      LET cmd_result <= SELECT Stdout FROM execve(argv=["sysctl", "-n", "hw.ncpu"])
      SELECT Line AS cores FROM parse_lines(filename=cmd_result[0].Stdout, accessor="data")
      LIMIT 1
```
![Screenshot from 2021-02-27 21-52-27](https://user-images.githubusercontent.com/9843422/109398591-8ae70680-7946-11eb-92e3-45f1624525fa.png)

So it runs all the queries but only emits results where the precondition matches. Not a big deal in this case but if the queries were long-running then it would be.
