### ISSUE TITLE
Server Artifacts Results tab does not refresh

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#939]
Version 0.5.6

For clients, on Collected Artifacts page the Results and Log tabs auto-refresh periodically.

For the Server Artifacts page these 2 tabs don't auto-refresh. One has to select another flow/row and then return to the one in progress to cause it to refresh.

**Comment by scudette** [comment]
That is actually not the case - client collected artifacts tab also do not automatically refresh. They both definitely should though :-).

**Comment by scudette** [comment]
How to test - create the following artifact in both server and client mode:
```yaml
name: Custom.Test.Counter
type: SERVER
sources:
  - query: |
      SELECT Unix FROM clock() 
      WHERE log(message=format(format="Counting %d", args=count()))
      LIMIT 200
```
